### ISSUE TITLE
[SNR]: Track down cause of currently off triggers results.

### ISSUE THREAD

**Issue by macrocosme** [isazi/SNR#3]
The triggers coming out of the pipeline are different than the correct results of the days prior to busy day merge. 

Potential causes: 
- data input (AMBER/src/...)
- change in evaluation for sigma cut (symmetric vs asymmetric)

**Comment by macrocosme** [comment]
It's not the sigma cut method.

**Comment by isazi** [comment]
Testing the whole pipeline at the moment, seems to work (at least on one test file).

**Comment by isazi** [comment]
I consider this issue solved for now.
